name: Upload Python Package

on:
  push:
    branches:
      - main  # 触发条件：当在main分支上有代码push时
  workflow_dispatch:  # 手动触发条件：当手动点击"Run workflow"按钮时

permissions:
  contents: read

jobs:
  publish_package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build and Publish
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'  # 仅在代码push到main分支时执行
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade setuptools wheel twine
          python setup.py sdist bdist_wheel
          twine upload dist/*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
