name: Upload Python Package

on:
  push:
    branches:
      - main  # 触发条件：当在main分支上有代码push时
  workflow_dispatch:  # 手动触发条件：当手动点击"Run workflow"按钮时

permissions:
  contents: read

jobs:
  check_version_and_publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Get previous version
      id: get_previous_version
      run: echo ::set-output name=version::$(git show main:setup.py | grep -oP "version=['\"]\K[^'\"]+")
    - name: Get current version
      id: get_current_version
      run: echo ::set-output name=version::$(cat setup.py | grep -oP "version=['\"]\K[^'\"]+")
    - name: Compare versions
      id: compare_versions
      run: echo ::set-output name=version_changed::${{ steps.get_previous_version.outputs.version != steps.get_current_version.outputs.version }}
    - name: Build and Publish
      if: steps.compare_versions.outputs.version_changed == 'true'
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade setuptools wheel twine
        python setup.py sdist bdist_wheel
        twine upload dist/*
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
