name: Upload Python Package

on:
  push:
    branches:
      - master  # 触发条件：当在master分支上有代码push时
  workflow_dispatch:  # 手动触发条件：当手动点击"Run workflow"按钮时

permissions:
  contents: read

jobs:
  publish_package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: master  # Explicitly specify the branch to checkout
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Replace 'x' with the desired Python version
      - name: Build and Publish
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'  # 仅在代码push到master分支时执行
        run: |
          python -m pip install --upgrade pip pipenv
          python -m pip install --upgrade setuptools wheel twine
          pipenv requirements > requirements.txt
          python -m pip install -r requirements.txt
          python setup.py sdist bdist_wheel
          twine upload dist/*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
